name: jmas_gestion
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2 #WEB
  shared_preferences: ^2.3.3 #Guardar token
  intl: ^0.19.0 #Fecha
  pdf: ^3.11.1 #PDF
  printing: ^5.13.4 #Imprimir
  path_provider: ^2.1.5 #Archivos sistema
  file_picker: ^8.1.6 #Seleccionar carpeta
  image_picker: ^1.1.2 #Seleccionar imagen   
  bitsdojo_window: ^0.1.0 #Tamaño pantaña
  qr_flutter: ^4.1.0 #QR
  flutter_svg: ^2.0.17 #SVG
  excel: ^4.0.6
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/sinFoto.jpg
    - assets/icons/
    - assets/images/logo_jmas_sf.png
    - assets/images/